### ISSUE TITLE
ng serve cannot find StorageService

### ISSUE THREAD

**Issue by MicMicMon** [dscheerens/ngx-webstorage-service#11]
Just upgraded to Angular 8.0.2, and now I get that when using `ng serve`:

```
ERROR in ./src/app/services/articule-storage.service.ts 84:12-26
"export 'StorageService' was not found in 'ngx-webstorage-service'
ERROR in ./src/app/services/articule-storage.service.ts 85:12-26
"export 'StorageService' was not found in 'ngx-webstorage-service'
```

I'm using a code similar to the one in the doc, and it worked fine until now.
Also, `ng build` works fine.

Any idea what could be going on?

**Comment by MicMicMon** [comment]
Ok, so I have the issue when using package `@angular-devkit/build-angular@0.800.4`, but using `@angular-devkit/build-angular@0.800.3` works fine for `ng serve`.

How to know if there's a bug to report un `build-angular`, or if it can be solved on the service side?

**Comment by MicMicMon** [comment]
Ok oups, actually already reported, problem seems to be on @angular/build side.
https://github.com/angular/angular-cli/issues/14876

Closing the issue here, sorry for the noise.

**Comment by dscheerens** [comment]
No problem. Glad to hear you found the problem :)
