### ISSUE TITLE
Trying to unit test this code, is giving error "this.storage.has is not a function"

### ISSUE THREAD

**Issue by sandeepsrao** [dscheerens/ngx-webstorage-service#4]
I'm writing unit test case for a component, where I'm checking if the storage has the key. But it gives me "this.storage.has is not a function". Because of this my test case is failing.
Is there a way to test this scenario?

I tried creating a mock like this:

`class MockStorageService implements StorageService {
    withDefaultTranscoder: any = null;
    has (token: string) {
      return isSaved;
    }
    get() {}
    set() {}
    remove() {}
    clear() {}
  }`

And I have added this in the providers array.

**Comment by dscheerens** [comment]
How did you add the provider? Like this?

```Typescript
providers: [
  { provide: SESSION_STORAGE, useClass: MockStorageService } // or LOCAL_STORAGE if you use that :)
]
```

**Comment by sandeepsrao** [comment]
Thanks for the help, I actually missed providing the MockStorageService separately along with the provider you have mentioned. So when I was testing, I was missing one of them. Now it is working.

**Comment by dscheerens** [comment]
Good to hear your issue has been resolved :+1:
