### ISSUE TITLE
Versioning data

### ISSUE THREAD

**Issue by LordLyng** [dscheerens/ngx-webstorage-service#6]
More a question than an issue...

Could this be used for versioned data in a pwa context, maybe implementing data migrations or something along those lines?

Any example would be more than welcome.

**Comment by dscheerens** [comment]
This library doesn't come with support for that and also a feature which I think is out of scope for this library. However, I guess that data versioning is something you can build on top of it.

Data versioning is quite a big topic on it's own, so without further details on how the versioning should work it is hard to provide an example. Nonetheless, assuming you have stored the data of your PWA in different properties, then you could make use of the storage transcoding feature to do data migrations.

First you might wish to create an intermediate model for storing your data along with a version identifier, e.g.:

```Typescript
interface ObjectSnapshot {
    version: number; // Version of the format/structure in which the object is stored
    payload: any; // The actual object that is stored
}
```

You could now create transcoders for each different model your application stores. For example if you have a `Preferences` model:

```Typescript
class Preferences {
    static MODEL_VERSION = 2;

    favoriteColor?: string;
    maxNumberOfItems: number;
}
```
Then a corresponding transcoder could look like:

```Typescript
export class PreferencesTranscoder implements StorageTranscoder<Preferences> {

    public encode(value: Preferences): string {
        return JSON.stringify({
               version: Preferences.MODEL_VERSION,
               payload: value
        });
    }

    public decode(value: string): Preferences {
        try {
            const { version, payload } = JSON.parse(value) as ObjectSnapshot;
            return {
                 favoriteColor: version >= 2 ? payload.favoriteColor : colorIdToHex(payload.favoriteColor)
                 maxNumberOfItems: version >= 2 ? payload.maxNumberOfItems : 10
            };
        } catch (error) {
            return undefined;
        }
    }

}

function colorIdToHex(colorId: string): string | undefined {
    switch (colorId) {
        case 'RED': return '#FF0000';
        case 'GREEN': return '#00FF00';
        case 'BLUE': return '#0000FF';
        default: return undefined;
    }
}
```

This is just one way of how you could achieve something like data versioning and migration. There are really a lot of different options also depending on you specific use case. Anyway, hope this helps to give you some pointers in the right direction :)
