### ISSUE TITLE
has and clear api's

### ISSUE THREAD

**Issue by beshad** [dscheerens/ngx-webstorage-service#7]
hi, do clear() and had() API's work with Angular 6? vscode tells me property 'clear (or had)' does not exist on type 'WebStorageService'? cheers

**Comment by dscheerens** [comment]
Yes, they do exist and work with Angular 6, however you need to have at least version **3.1.0** of `ngx-webstorage-service` installed.

Which version do you have installed?

**Comment by beshad** [comment]
thanks for reply. yes i have the version 3.1.1 installed. i used `remove()` to clear the session at logout but also need `has();` functionto check in couple places. any ideas?

**Comment by dscheerens** [comment]
Hmm it is working for me (see screenshot below):

![Screenshot](https://preview.ibb.co/jiNfqp/screenshot.png)

Can you post an example of the code (complete file if possible) where you are using the `has` function?

**Comment by beshad** [comment]
cheers for the screenshot. it showed my error. I feel stupid now! 

i was following the instructions on npm (https://www.npmjs.com/package/angular-webstorage-service) and importing `// import { StorageServiceModule} from 'angular-webstorage-service';` not ngx

didn't see the Important note on top of the page. problem is solved now and i am closing this issue. ta
