### ISSUE TITLE
SessionStorage used instead of LocalStorage

### ISSUE THREAD

**Issue by SergioV85** [dscheerens/ngx-webstorage-service#9]
In the latest version for both injection tokens used Session storage.
Please, see this line of code:
https://github.com/dscheerens/ngx-webstorage-service/commit/8786c26c1e0556fe5f9809a20230124172ff3b15#diff-0357eeed7350b48cbfb06c77e97c2c9bR36

**Comment by dscheerens** [comment]
Thanks for reporting the issue and also providing a fix! 👍 

The PR has been merged and I have just released a new version that includes the fix (v4.0.1)
